### ISSUE TITLE
Error in vignette building

### ISSUE THREAD

**Issue by pkrog** [SciDoPhenIA/phenomis#1]
Hi Étienne,
I got the following error when trying to build the vignette:
```
File figures/permanent/phenomis_methods.png not found in resource path
Error: processing vignette 'phenomis.Rmd' failed with diagnostics:
pandoc document conversion failed with error 99
```

**Comment by ethevenot** [comment]
The .Rmd relies on images stored in the figures/permanent subfolder from the vignettes folder. So the .Rmd must be run within the vignettes working directory (alternatively, copy the figures/permanent folder in your working directory).
